// Class 00 — Successful Completion
exports.SUCCESSFUL_COMPLETION = '00000'

// Class 01 — Warning
exports.WARNING = '01000'
exports.DYNAMIC_RESULT_SETS_RETURNED = '0100C'
exports.IMPLICIT_ZERO_BIT_PADDING = '01008'
exports.NULL_VALUE_ELIMINATED_IN_SET_FUNCTION = '01003'
exports.PRIVILEGE_NOT_GRANTED = '01007'
exports.PRIVILEGE_NOT_REVOKED = '01006'
exports.STRING_DATA_RIGHT_TRUNCATION = '01004'
exports.DEPRECATED_FEATURE = '01P01'

// Class 02 — No Data (this is also a warning class per the SQL standard)
exports.NO_DATA = '02000'
exports.NO_ADDITIONAL_DYNAMIC_RESULT_SETS_RETURNED = '02001'

// Class 03 — SQL Statement Not Yet Complete
exports.SQL_STATEMENT_NOT_YET_COMPLETE = '03000'

// Class 08 — Connection Exception
exports.CONNECTION_EXCEPTION = '08000'
exports.CONNECTION_DOES_NOT_EXIST = '08003'
exports.CONNECTION_FAILURE = '08006'
exports.SQLCLIENT_UNABLE_TO_ESTABLISH_SQLCONNECTION = '08001'
exports.SQLSERVER_REJECTED_ESTABLISHMENT_OF_SQLCONNECTION = '08004'
exports.TRANSACTION_RESOLUTION_UNKNOWN = '08007'
exports.PROTOCOL_VIOLATION = '08P01'

// Class 09 — Triggered Action Exception
exports.TRIGGERED_ACTION_EXCEPTION = '09000'

// Class 0A — Feature Not Supported
exports.FEATURE_NOT_SUPPORTED = '0A000'

// Class 0B — Invalid Transaction Initiation
exports.INVALID_TRANSACTION_INITIATION = '0B000'

// Class 0F — Locator Exception
exports.LOCATOR_EXCEPTION = '0F000'
exports.INVALID_LOCATOR_SPECIFICATION = '0F001'

// Class 0L — Invalid Grantor
exports.INVALID_GRANTOR = '0L000'
exports.INVALID_GRANT_OPERATION = '0LP01'

// Class 0P — Invalid Role Specification
exports.INVALID_ROLE_SPECIFICATION = '0P000'

// Class 0Z — Diagnostics Exception
exports.DIAGNOSTICS_EXCEPTION = '0Z000'
exports.STACKED_DIAGNOSTICS_ACCESSED_WITHOUT_ACTIVE_HANDLER = '0Z002'

// Class 20 — Case Not Found
exports.CASE_NOT_FOUND = '20000'

// Class 21 — Cardinality Violation
exports.CARDINALITY_VIOLATION = '21000'

// Class 22 — Data Exception
exports.DATA_EXCEPTION = '22000'
exports.ARRAY_SUBSCRIPT_ERROR = '2202E'
exports.CHARACTER_NOT_IN_REPERTOIRE = '22021'
exports.DATETIME_FIELD_OVERFLOW = '22008'
exports.DIVISION_BY_ZERO = '22012'
exports.ERROR_IN_ASSIGNMENT = '22005'
exports.ESCAPE_CHARACTER_CONFLICT = '2200B'
exports.INDICATOR_OVERFLOW = '22022'
exports.INTERVAL_FIELD_OVERFLOW = '22015'
exports.INVALID_ARGUMENT_FOR_LOGARITHM = '2201E'
exports.INVALID_ARGUMENT_FOR_NTILE_FUNCTION = '22014'
exports.INVALID_ARGUMENT_FOR_NTH_VALUE_FUNCTION = '22016'
exports.INVALID_ARGUMENT_FOR_POWER_FUNCTION = '2201F'
exports.INVALID_ARGUMENT_FOR_WIDTH_BUCKET_FUNCTION = '2201G'
exports.INVALID_CHARACTER_VALUE_FOR_CAST = '22018'
exports.INVALID_DATETIME_FORMAT = '22007'
exports.INVALID_ESCAPE_CHARACTER = '22019'
exports.INVALID_ESCAPE_OCTET = '2200D'
exports.INVALID_ESCAPE_SEQUENCE = '22025'
exports.NONSTANDARD_USE_OF_ESCAPE_CHARACTER = '22P06'
exports.INVALID_INDICATOR_PARAMETER_VALUE = '22010'
exports.INVALID_PARAMETER_VALUE = '22023'
exports.INVALID_REGULAR_EXPRESSION = '2201B'
exports.INVALID_ROW_COUNT_IN_LIMIT_CLAUSE = '2201W'
exports.INVALID_ROW_COUNT_IN_RESULT_OFFSET_CLAUSE = '2201X'
exports.INVALID_TIME_ZONE_DISPLACEMENT_VALUE = '22009'
exports.INVALID_USE_OF_ESCAPE_CHARACTER = '2200C'
exports.MOST_SPECIFIC_TYPE_MISMATCH = '2200G'
exports.NULL_VALUE_NOT_ALLOWED = '22004'
exports.NULL_VALUE_NO_INDICATOR_PARAMETER = '22002'
exports.NUMERIC_VALUE_OUT_OF_RANGE = '22003'
exports.STRING_DATA_LENGTH_MISMATCH = '22026'
exports.STRING_DATA_RIGHT_TRUNCATION = '22001'
exports.SUBSTRING_ERROR = '22011'
exports.TRIM_ERROR = '22027'
exports.UNTERMINATED_C_STRING = '22024'
exports.ZERO_LENGTH_CHARACTER_STRING = '2200F'
exports.FLOATING_POINT_EXCEPTION = '22P01'
exports.INVALID_TEXT_REPRESENTATION = '22P02'
exports.INVALID_BINARY_REPRESENTATION = '22P03'
exports.BAD_COPY_FILE_FORMAT = '22P04'
exports.UNTRANSLATABLE_CHARACTER = '22P05'
exports.NOT_AN_XML_DOCUMENT = '2200L'
exports.INVALID_XML_DOCUMENT = '2200M'
exports.INVALID_XML_CONTENT = '2200N'
exports.INVALID_XML_COMMENT = '2200S'
exports.INVALID_XML_PROCESSING_INSTRUCTION = '2200T'

// Class 23 — Integrity Constraint Violation
exports.INTEGRITY_CONSTRAINT_VIOLATION = '23000'
exports.RESTRICT_VIOLATION = '23001'
exports.NOT_NULL_VIOLATION = '23502'
exports.FOREIGN_KEY_VIOLATION = '23503'
exports.UNIQUE_VIOLATION = '23505'
exports.CHECK_VIOLATION = '23514'
exports.EXCLUSION_VIOLATION = '23P01'

// Class 24 — Invalid Cursor State
exports.INVALID_CURSOR_STATE = '24000'

// Class 25 — Invalid Transaction State
exports.INVALID_TRANSACTION_STATE = '25000'
exports.ACTIVE_SQL_TRANSACTION = '25001'
exports.BRANCH_TRANSACTION_ALREADY_ACTIVE = '25002'
exports.HELD_CURSOR_REQUIRES_SAME_ISOLATION_LEVEL = '25008'
exports.INAPPROPRIATE_ACCESS_MODE_FOR_BRANCH_TRANSACTION = '25003'
exports.INAPPROPRIATE_ISOLATION_LEVEL_FOR_BRANCH_TRANSACTION = '25004'
exports.NO_ACTIVE_SQL_TRANSACTION_FOR_BRANCH_TRANSACTION = '25005'
exports.READ_ONLY_SQL_TRANSACTION = '25006'
exports.SCHEMA_AND_DATA_STATEMENT_MIXING_NOT_SUPPORTED = '25007'
exports.NO_ACTIVE_SQL_TRANSACTION = '25P01'
exports.IN_FAILED_SQL_TRANSACTION = '25P02'

// Class 26 — Invalid SQL Statement Name
exports.INVALID_SQL_STATEMENT_NAME = '26000'

// Class 27 — Triggered Data Change Violation
exports.TRIGGERED_DATA_CHANGE_VIOLATION = '27000'

// Class 28 — Invalid Authorization Specification
exports.INVALID_AUTHORIZATION_SPECIFICATION = '28000'
exports.INVALID_PASSWORD = '28P01'

// Class 2B — Dependent Privilege Descriptors Still Exist
exports.DEPENDENT_PRIVILEGE_DESCRIPTORS_STILL_EXIST = '2B000'
exports.DEPENDENT_OBJECTS_STILL_EXIST = '2BP01'

// Class 2D — Invalid Transaction Termination
exports.INVALID_TRANSACTION_TERMINATION = '2D000'

// Class 2F — SQL Routine Exception
exports.SQL_ROUTINE_EXCEPTION = '2F000'
exports.FUNCTION_EXECUTED_NO_RETURN_STATEMENT = '2F005'
exports.MODIFYING_SQL_DATA_NOT_PERMITTED = '2F002'
exports.PROHIBITED_SQL_STATEMENT_ATTEMPTED = '2F003'
exports.READING_SQL_DATA_NOT_PERMITTED = '2F004'

// Class 34 — Invalid Cursor Name
exports.INVALID_CURSOR_NAME = '34000'

// Class 38 — External Routine Exception
exports.EXTERNAL_ROUTINE_EXCEPTION = '38000'
exports.CONTAINING_SQL_NOT_PERMITTED = '38001'
exports.MODIFYING_SQL_DATA_NOT_PERMITTED = '38002'
exports.PROHIBITED_SQL_STATEMENT_ATTEMPTED = '38003'
exports.READING_SQL_DATA_NOT_PERMITTED = '38004'

// Class 39 — External Routine Invocation Exception
exports.EXTERNAL_ROUTINE_INVOCATION_EXCEPTION = '39000'
exports.INVALID_SQLSTATE_RETURNED = '39001'
exports.NULL_VALUE_NOT_ALLOWED = '39004'
exports.TRIGGER_PROTOCOL_VIOLATED = '39P01'
exports.SRF_PROTOCOL_VIOLATED = '39P02'

// Class 3B — Savepoint Exception
exports.SAVEPOINT_EXCEPTION = '3B000'
exports.INVALID_SAVEPOINT_SPECIFICATION = '3B001'

// Class 3D — Invalid Catalog Name
exports.INVALID_CATALOG_NAME = '3D000'

// Class 3F — Invalid Schema Name
exports.INVALID_SCHEMA_NAME = '3F000'

// Class 40 — Transaction Rollback
exports.TRANSACTION_ROLLBACK = '40000'
exports.TRANSACTION_INTEGRITY_CONSTRAINT_VIOLATION = '40002'
exports.SERIALIZATION_FAILURE = '40001'
exports.STATEMENT_COMPLETION_UNKNOWN = '40003'
exports.DEADLOCK_DETECTED = '40P01'

// Class 42 — Syntax Error or Access Rule Violation
exports.SYNTAX_ERROR_OR_ACCESS_RULE_VIOLATION = '42000'
exports.SYNTAX_ERROR = '42601'
exports.INSUFFICIENT_PRIVILEGE = '42501'
exports.CANNOT_COERCE = '42846'
exports.GROUPING_ERROR = '42803'
exports.WINDOWING_ERROR = '42P20'
exports.INVALID_RECURSION = '42P19'
exports.INVALID_FOREIGN_KEY = '42830'
exports.INVALID_NAME = '42602'
exports.NAME_TOO_LONG = '42622'
exports.RESERVED_NAME = '42939'
exports.DATATYPE_MISMATCH = '42804'
exports.INDETERMINATE_DATATYPE = '42P18'
exports.COLLATION_MISMATCH = '42P21'
exports.INDETERMINATE_COLLATION = '42P22'
exports.WRONG_OBJECT_TYPE = '42809'
exports.UNDEFINED_COLUMN = '42703'
exports.UNDEFINED_FUNCTION = '42883'
exports.UNDEFINED_TABLE = '42P01'
exports.UNDEFINED_PARAMETER = '42P02'
exports.UNDEFINED_OBJECT = '42704'
exports.DUPLICATE_COLUMN = '42701'
exports.DUPLICATE_CURSOR = '42P03'
exports.DUPLICATE_DATABASE = '42P04'
exports.DUPLICATE_FUNCTION = '42723'
exports.DUPLICATE_PREPARED_STATEMENT = '42P05'
exports.DUPLICATE_SCHEMA = '42P06'
exports.DUPLICATE_TABLE = '42P07'
exports.DUPLICATE_ALIAS = '42712'
exports.DUPLICATE_OBJECT = '42710'
exports.AMBIGUOUS_COLUMN = '42702'
exports.AMBIGUOUS_FUNCTION = '42725'
exports.AMBIGUOUS_PARAMETER = '42P08'
exports.AMBIGUOUS_ALIAS = '42P09'
exports.INVALID_COLUMN_REFERENCE = '42P10'
exports.INVALID_COLUMN_DEFINITION = '42611'
exports.INVALID_CURSOR_DEFINITION = '42P11'
exports.INVALID_DATABASE_DEFINITION = '42P12'
exports.INVALID_FUNCTION_DEFINITION = '42P13'
exports.INVALID_PREPARED_STATEMENT_DEFINITION = '42P14'
exports.INVALID_SCHEMA_DEFINITION = '42P15'
exports.INVALID_TABLE_DEFINITION = '42P16'
exports.INVALID_OBJECT_DEFINITION = '42P17'

// Class 44 — WITH CHECK OPTION Violation
exports.WITH_CHECK_OPTION_VIOLATION = '44000'

// Class 53 — Insufficient Resources
exports.INSUFFICIENT_RESOURCES = '53000'
exports.DISK_FULL = '53100'
exports.OUT_OF_MEMORY = '53200'
exports.TOO_MANY_CONNECTIONS = '53300'
exports.CONFIGURATION_LIMIT_EXCEEDED = '53400'

// Class 54 — Program Limit Exceeded
exports.PROGRAM_LIMIT_EXCEEDED = '54000'
exports.STATEMENT_TOO_COMPLEX = '54001'
exports.TOO_MANY_COLUMNS = '54011'
exports.TOO_MANY_ARGUMENTS = '54023'

// Class 55 — Object Not In Prerequisite State
exports.OBJECT_NOT_IN_PREREQUISITE_STATE = '55000'
exports.OBJECT_IN_USE = '55006'
exports.CANT_CHANGE_RUNTIME_PARAM = '55P02'
exports.LOCK_NOT_AVAILABLE = '55P03'

// Class 57 — Operator Intervention
exports.OPERATOR_INTERVENTION = '57000'
exports.QUERY_CANCELED = '57014'
exports.ADMIN_SHUTDOWN = '57P01'
exports.CRASH_SHUTDOWN = '57P02'
exports.CANNOT_CONNECT_NOW = '57P03'
exports.DATABASE_DROPPED = '57P04'

// Class 58 — System Error (errors external to PostgreSQL itself)
exports.SYSTEM_ERROR = '58000'
exports.IO_ERROR = '58030'
exports.UNDEFINED_FILE = '58P01'
exports.DUPLICATE_FILE = '58P02'

// Class F0 — Configuration File Error
exports.CONFIG_FILE_ERROR = 'F0000'
exports.LOCK_FILE_EXISTS = 'F0001'

// Class HV — Foreign Data Wrapper Error (SQL/MED)
exports.FDW_ERROR = 'HV000'
exports.FDW_COLUMN_NAME_NOT_FOUND = 'HV005'
exports.FDW_DYNAMIC_PARAMETER_VALUE_NEEDED = 'HV002'
exports.FDW_FUNCTION_SEQUENCE_ERROR = 'HV010'
exports.FDW_INCONSISTENT_DESCRIPTOR_INFORMATION = 'HV021'
exports.FDW_INVALID_ATTRIBUTE_VALUE = 'HV024'
exports.FDW_INVALID_COLUMN_NAME = 'HV007'
exports.FDW_INVALID_COLUMN_NUMBER = 'HV008'
exports.FDW_INVALID_DATA_TYPE = 'HV004'
exports.FDW_INVALID_DATA_TYPE_DESCRIPTORS = 'HV006'
exports.FDW_INVALID_DESCRIPTOR_FIELD_IDENTIFIER = 'HV091'
exports.FDW_INVALID_HANDLE = 'HV00B'
exports.FDW_INVALID_OPTION_INDEX = 'HV00C'
exports.FDW_INVALID_OPTION_NAME = 'HV00D'
exports.FDW_INVALID_STRING_LENGTH_OR_BUFFER_LENGTH = 'HV090'
exports.FDW_INVALID_STRING_FORMAT = 'HV00A'
exports.FDW_INVALID_USE_OF_NULL_POINTER = 'HV009'
exports.FDW_TOO_MANY_HANDLES = 'HV014'
exports.FDW_OUT_OF_MEMORY = 'HV001'
exports.FDW_NO_SCHEMAS = 'HV00P'
exports.FDW_OPTION_NAME_NOT_FOUND = 'HV00J'
exports.FDW_REPLY_HANDLE = 'HV00K'
exports.FDW_SCHEMA_NOT_FOUND = 'HV00Q'
exports.FDW_TABLE_NOT_FOUND = 'HV00R'
exports.FDW_UNABLE_TO_CREATE_EXECUTION = 'HV00L'
exports.FDW_UNABLE_TO_CREATE_REPLY = 'HV00M'
exports.FDW_UNABLE_TO_ESTABLISH_CONNECTION = 'HV00N'

// Class P0 — PL/pgSQL Error
exports.PLPGSQL_ERROR = 'P0000'
exports.RAISE_EXCEPTION = 'P0001'
exports.NO_DATA_FOUND = 'P0002'
exports.TOO_MANY_ROWS = 'P0003'

// Class XX — Internal Error
exports.INTERNAL_ERROR = 'XX000'
exports.DATA_CORRUPTED = 'XX001'
exports.INDEX_CORRUPTED = 'XX002'
